name: Build

on:
  push:

env:
  python-version: '3.8'
  poetry-version: '1.8.2'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: git=1:2.30.2-1+deb11u2 libyaml-0-2 libssl-dev libcurl4-openssl-dev gcc python3-dev libyaml-dev
        version: 1.0
      - uses: actions/checkout@v4
      - run: ls -l
      - name: Checkout
        run: |
         echo "hello" > test.txt 
      - uses: ./.github/actions/test
        with:
          shell_ex: "ls -l"
          poetry_version: ${{ env.poetry-version }}
      - uses: ./.github/actions/test
        with:
          shell_ex: "cat test.txt"
          poetry_version: ${{ env.poetry_version }}

  call-workflow-in-local-repo:
    uses: ./.github/workflows/test.yml
