name: Build

on:
  push:

env:
  python-version: '3.8'
  poetry-version: '1.8.2'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: ls -l
      - name: Checkout
        run: |
         echo "hello" > test.txt 
      - uses: ./.github/actions/test
        with:
          shell_ex: "ls -l"
          poetry_version: ${{ python_version }}
      - uses: ./.github/actions/test
        with:
          shell_ex: "cat test.txt"
          poetry_version: '1.2.3'
    with:
      python-version: ${{ env.python-version }}

  call-workflow-in-local-repo:
    uses: ./.github/workflows/test.yml
