name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        run: |
         echo "hello" > test.txt 
      - uses: ./.github/test.yml
      # - uses: .github/workflows/test.yml
      - uses: ./actions/test.yml
      - uses: ./test.yml
