name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: ls -l
      - name: Checkout
        run: |
         echo "hello" > test.txt 
      - uses: ./.github/actions/test
        with:
          shell_ex: "ls -l"
          poetry-version: '1.2.3'
      - uses: ./.github/actions/test
        with:
          shell_ex: "cat test.txt"
          poetry_version: '1.2.3'
  call-workflow-in-local-repo:
    uses: ./.github/workflows/test.yml
