name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: ls -l
      - name: Checkout
        run: |
         echo "hello" > test.txt 
      - uses: ./actions/test
  call-workflow-in-local-repo:
    uses: ./.github/workflows/test
    with:
      shell_ex: "ls -l"
  call-workflow-in-local-repo2:
    uses: ./.github/workflows/test
    with:
      shell_ex: "cat test.txt"