name: Protect master branch

on:
  push:
    branches:
      - master
  pull_request: 
    branches: 
      - master
      
jobs:
  protect:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Check if base branch needs to be updated
      run: |
        if [[ ${{ github.event.pull_request.base.ref }} == 'master' && (${{ github.event.pull_request.head.ref }} != 'develop' && !(${{ github.event.pull_request.head.ref }} | contains('hotfix/')) ) ]]; then
          echo "name is hotfix/** and develop"
          exit 1
        fi
