name: Protect master branch

on:
  push:
    branches:
      - master
  pull_request: 
    branches: 
      - master
      
jobs:
  protect:
    runs-on: ubuntu-latest

    steps:
    - name: Check if branch is develop
      run: |
        if [ $GITHUB_REF != 'refs/heads/develop' ]; then
          exit 0
        fi
    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: |
          Only force push from develop branch is allowed !
        reactions: rocket
