name: Protect master branch

on:
  push:
    branches:
      - master
  pull_request: 
    branches: 
      - master
      
jobs:
  protect:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - name: Check if branch is develop
      env:
        URL: ${{ github.event.pull_request.comments_url }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MESSAGE: '"Пр может быть только от develop ветки"'
      run: |
        if [ $GITHUB_REF != 'refs/heads/develop' ]; then
            curl \
            -X POST \
            $URL \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data '{ "body":"$MESSAGE" }'
          exit 1
        fi
