name: Protect master branch

on:
  push:
    branches:
      - master

jobs:
  protect:
    runs-on: ubuntu-latest

    steps:
    - name: Check if branch is develop
      run: |
        echo "$GITHUB_ENV";
        echo "$NEW_VARIABLE";
