name: Protect master branch

on:
  push:
    branches:
      - master
  pull_request: 
    branches: 
      - master
      
jobs:
  protect:
    runs-on: ubuntu-latest

    steps:
    - name: Check if branch is develop
      run: |
        if [ $GITHUB_REF != 'refs/heads/develop' ]; then
          echo "Only force push from develop branch is allowed"
          exit 1
        fi