name: Protect master branch

on:
  push:
    branches:
      - master
  pull_request: 
    branches: 
      - master
      
jobs:
  protect:
    runs-on: ubuntu-latest

    steps:
    - name: Check if branch is develop
      run: |
        if [ $GITHUB_REF != 'refs/heads/develop' ]; then
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X POST -d '{"body": "Only force push from develop branch is allowed"}' "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
          exit 1
        fi