name: Protect master branch

on:
  push:

jobs:
  protect:
    runs-on: ubuntu-latest

    steps:
    - name: Check if branch is develop
      run: |
        echo "$GITHUB_ENV";
        echo NEW_VARIABLE:: "$NEW_VARIABLE";
