name: Gitflow protect master branch

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  protect:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check if base branch needs to be updated
        env:
          COMMENTS_URL: https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash ./.github/scripts/check_branch.sh ${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.ref }}

      - name: Check if head branch is ancestor of base branch
        run: |
          git fetch origin develop
          git merge-base --is-ancestor ${{ github.event.pull_request.head.ref }} develop