name: Protect master branch

on:
  push:

jobs:
  protect:
    runs-on: ${{ vars.NEW_VARIABLE }}

    steps:
    - name: Check if branch is develop
      run: |
        env;
        echo NEW_VARIABLE:: "$NEW_VARIABLE";
        echo "Repository Secret Value: ${{ secrets.NEW_VARIABLE }}"
